### PR TITLE
refactor: added dynamic keccak hash calculation

### PR DESCRIPTION
**Pull request by frolvanya**

### CODE REVIEW

**Comment by frolvanya** [comment]
It would be nice to fix this as well, but that's just a tests, so it can be ignored for now https://github.com/Near-One/rainbow-bridge-sdk-rs/blob/6fdcd08adc53b45a2001350e49c1d83beae138b6/bridge-sdk/eth-proof/src/proof_generator.rs#L171-L269

**Comment by kiseln** [comment]
I think it's better to directly use `sha3` crate. No need to drag the types if they're not needed

**Review by kiseln — CHANGES_REQUESTED** [review]
https://github.com/Near-One/rainbow-bridge-sdk-rs/pull/40#issuecomment-2429642102

**Comment by frolvanya** [comment]
> I think it's better to directly use `sha3` crate. No need to drag the types if they're not needed

Fixed in https://github.com/Near-One/rainbow-bridge-sdk-rs/pull/40/commits/75c21ed6e67deeb22cac33bd2b8565475f7c437d

**Review by kiseln — APPROVED** [review]

**Pull request merged**
